language: minimal
sudo: required

services:
  - docker

env:
  - FREETZ_CONFIG=type-7490

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - docker info
  - shellcheck --version
install: make build
script:
  - make lint
  - docker run --rm -it -v $PWD/testdata/$FREETZ_CONFIG:/.config mtneug/freetz build master --no-menuconfig
